export const CART_ITEMS_FETCH_STARTED = 'CART_ITEMS_FETCH_STARTED';
export const CART_ITEMS_FETCH_COMPLETED = 'CART_ITEMS_FETCH_COMPLETED';
export const CART_ITEMS_FETCH_FAILED = 'CART_ITEMS_FETCH_FAILED';

export const CART_ITEM_ADD_STARTED = 'CART_ITEM_ADD_STARTED';
export const CART_ITEM_ADD_COMPLETED = 'CART_ITEM_ADD_COMPLETED';
export const CART_ITEM_ADD_FAILED = 'CART_ITEM_ADD_FAILED';

export const CART_ITEM_REMOVE_STARTED = 'CART_ITEM_REMOVE_STARTED';
export const CART_ITEM_REMOVE_COMPLETED = 'CART_ITEM_REMOVE_COMPLETED';
export const CART_ITEM_REMOVE_FAILED = 'CART_ITEM_REMOVE_FAILED';

export const CART_ITEM_UPDATE_STARTED = 'CART_ITEM_UPDATE_STARTED';
export const CART_ITEM_UPDATE_COMPLETED = 'CART_ITEM_UPDATE_COMPLETED';
export const CART_ITEM_UPDATE_FAILED = 'CART_ITEM_UPDATE_FAILED';

export const CART_FETCH_STARTED = 'CART_FETCH_STARTED';
export const CART_FETCH_COMPLETED = 'CART_FETCH_COMPLETED';
export const CART_FETCH_FAILED = 'CART_FETCH_FAILED';
