export const WISHLIST_FETCH_STARTED = 'WISHLIST_FETCH_STARTED';
export const WISHLIST_FETCH_COMPLETED = 'WISHLIST_FETCH_COMPLETED';
export const WISHLIST_FETCH_FAILED = 'WISHLIST_FETCH_FAILED';

export const WISHLIST_ITEM_ADD_STARTED = 'WISHLIST_ITEM_ADD_STARTED';
export const WISHLIST_ITEM_ADD_COMPLETED = 'WISHLIST_ITEM_ADD_COMPLETED';
export const WISHLIST_ITEM_ADD_FAILED = 'WISHLIST_ITEM_ADD_FAILED';

export const WISHLIST_ITEM_REMOVE_STARTED = 'WISHLIST_ITEM_REMOVE_STARTED';
export const WISHLIST_ITEM_REMOVE_COMPLETED = 'WISHLIST_ITEM_REMOVE_COMPLETED';
export const WISHLIST_ITEM_REMOVE_FAILED = 'WISHLIST_ITEM_REMOVE_FAILED';