export const POST_PAYMENT_STARTED = 'POST_PAYMENT_STARTED';
export const POST_PAYMENT_COMPLETED = 'POST_PAYMENT_COMPLETED';
export const POST_PAYMENT_FAILED = 'POST_PAYMENT_FAILED';


export const PAYMENT_ITEMS_FETCH_STARTED = 'PAYMENT_ITEMS_FETCH_STARTED';
export const PAYMENT_ITEMS_FETCH_COMPLETED = 'PAYMENT_ITEMS_FETCH_COMPLETED';
export const PAYMENT_ITEMS_FETCH_FAILED = 'PAYMENT_ITEMS_FETCH_FAILED';