export const COUPON_FIELD_CHANGED = 'COUPON_FIELD_CHANGED';
export const COUPON_FETCH_STARTED = 'COUPON_FETCH_STARTED';
export const COUPON_FETCH_COMPLETED = 'COUPON_FETCH_COMPLETED';
export const COUPON_FETCH_FAILED = 'COUPON_FETCH_FAILED';
export const COUPON_REDEEMED = 'COUPON_REDEEMED';
