export const SEARCH_PRODUCT_FETCH_STARTED = 'SEARCH_PRODUCT_FETCH_STARTED';
export const SEARCH_PRODUCT_FETCH_COMPLETED = 'SEARCH_PRODUCT_FETCH_COMPLETED';
export const SEARCH_PRODUCT_FETCH_FAILED = 'SEARCH_PRODUCT_FETCH_FAILED';
