export const POST_REVIEW_STARTED = 'POST_REVIEW_STARTED';
export const POST_REVIEW_COMPLETED = 'POST_REVIEW_COMPLETED';
export const POST_REVIEW_FAILED = 'POST_REVIEW_FAILED';

export const FETCH_REVIEWS_STARTED = 'FETCH_REVIEWS_STARTED';
export const FETCH_REVIEWS_COMPLETED = 'FETCH_REVIEWS_COMPLETED';
export const FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED';