export const SINGLE_PRODUCT_FETCH_STARTED = 'SINGLE_PRODUCT_FETCH_STARTED';
export const SINGLE_PRODUCT_FETCH_COMPLETED = 'SINGLE_PRODUCT_FETCH_COMPLETED';
export const SINGLE_PRODUCT_FETCH_FAILED = 'SINGLE_PRODUCT_FETCH_FAILED';
