export const POST_ORDER_STARTED = 'POST_ORDER_STARTED';
export const POST_ORDER_COMPLETED = 'POST_ORDER_COMPLETED';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';

export const ORDER_ITEMS_FETCH_STARTED = 'ORDER_ITEMS_FETCH_STARTED';
export const ORDER_ITEMS_FETCH_COMPLETED = 'ORDER_ITEMS_FETCH_COMPLETED';
export const ORDER_ITEMS_FETCH_FAILED = 'ORDER_ITEMS_FETCH_FAILED';