export const USER_FETCH_STARTED = 'USER_FETCH_STARTED';
export const USER_FETCH_COMPLETED = 'USER_FETCH_COMPLETED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const USER_UPDATE_STARTED = 'USER_UPDATE_STARTED';
export const USER_UPDATE_COMPLETED = 'USER_UPDATE_COMPLETED';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const CHANGE_PASSWORD_STARTED = 'CHANGE_PASSWORD_STARTED';
export const CHANGE_PASSWORD_COMPLETED = 'CHANGE_PASSWORD_COMPLETED';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const AUTHENTICATION_IDENTITY_CLEARED = 'AUTHENTICATION_IDENTITY_CLEARED';