export const CATEGORY_FETCH_STARTED = 'CATEGORY_FETCH_STARTED';
export const CATEGORY_FETCH_COMPLETED = 'CATEGORY_FETCH_COMPLETED';
export const CATEGORY_FETCH_FAILED = 'CATEGORY_FETCH_FAILED';

export const CATEGORY_PRODUCTS_FETCH_STARTED = 'CATEGORY_PRODUCTS_FETCH_STARTED';
export const CATEGORY_PRODUCTS_FETCH_COMPLETED = 'CATEGORY_PRODUCTS_FETCH_COMPLETED';
export const CATEGORY_PRODUCTS_FETCH_FAILED = 'CATEGORY_PRODUCTS_FETCH_FAILED';