export const POST_INVOICE_STARTED = 'POST_INVOICE_STARTED';
export const POST_INVOICE_COMPLETED = 'POST_INVOICE_COMPLETED';
export const POST_INVOICE_FAILED = 'POST_INVOICE_FAILED';


export const INVOICE_ITEMS_FETCH_STARTED = 'INVOICE_ITEMS_FETCH_STARTED';
export const INVOICE_ITEMS_FETCH_COMPLETED = 'INVOICE_ITEMS_FETCH_COMPLETED';
export const INVOICE_ITEMS_FETCH_FAILED = 'INVOICE_ITEMS_FETCH_FAILED';