export const GALLERYITEMS_FETCH_STARTED = 'GALLERYITEMS_FETCH_STARTED';
export const GALLERYITEMS_FETCH_COMPLETED = 'GALLERYITEMS_FETCH_COMPLETED';
export const GALLERYITEMS_FETCH_FAILED = 'GALLERYITEMS_FETCH_FAILED';
